### ISSUE TITLE
Error with MySql sync

### ISSUE THREAD

**Issue by McKay1717** [peeringdb/peeringdb-py#22]
Hello

I've installed on Ubuntu 18.10 this tools with pip.
But i've got an error when I run  peeringdb sync with mysql but none with sqlite.

```
Traceback (most recent call last):
  File "/usr/local/bin/peeringdb", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/peeringdb/cli.py", line 164, in sync
    db.sync()
  File "/usr/local/lib/python2.7/dist-packages/peeringdb/localdb.py", line 123, in sync
    self.create()
  File "/usr/local/lib/python2.7/dist-packages/peeringdb/localdb.py", line 116, in create
    call_command('migrate', interactive=False)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 191, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 59, in applied_migrations
    self.ensure_schema()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 49, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 164, in cursor
    cursor = self.make_cursor(self._cursor())
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 135, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 119, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 278, in get_new_connection
    conn.encoders[SafeBytes] = conn.encoders[bytes]
KeyError: <type 'str'>
```

Dependancy install
```
Requirement already satisfied: twentyc.rpc>=0.3.4 in /usr/local/lib/python2.7/dist-packages (from peeringdb) (0.3.5)
Requirement already satisfied: PyYAML>=3.11 in /usr/lib/python2.7/dist-packages (from peeringdb) (3.12)
Requirement already satisfied: munge>=0.1.5 in /usr/local/lib/python2.7/dist-packages (from peeringdb) (0.6.0)
Requirement already satisfied: click>=5.1 in /usr/local/lib/python2.7/dist-packages (from peeringdb) (6.7)
Requirement already satisfied: requests>=2.10.0 in /usr/lib/python2.7/dist-packages (from twentyc.rpc>=0.3.4->peeringdb) (2.18.4)
Requirement already satisfied: future<1,>=0.15.2 in /usr/lib/python2.7/dist-packages (from munge>=0.1.5->peeringdb) (0.15.2)
Installing collected packages: peeringdb
Successfully installed peeringdb-0.6.1
```
```
The directory '/tmp/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/nicolas/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: django<1.9,>1.8 in /usr/local/lib/python2.7/dist-packages (1.8.19)
You are using pip version 18.1, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The directory '/tmp/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/nicolas/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: django_peeringdb<0.5.0,==0.4.0 in /usr/local/lib/python2.7/dist-packages (0.4.0)
Requirement already satisfied: django_countries>=0.1.0 in /usr/local/lib/python2.7/dist-packages (from django_peeringdb<0.5.0,==0.4.0) (5.3.2)
Requirement already satisfied: django_handleref<0.2.0,>=0.1.4 in /usr/local/lib/python2.7/dist-packages (from django_peeringdb<0.5.0,==0.4.0) (0.1.5)
Requirement already satisfied: django_inet<0.4,>=0.3.2 in /usr/local/lib/python2.7/dist-packages (from django_peeringdb<0.5.0,==0.4.0) (0.3.2)
Requirement already satisfied: twentyc.rpc<0.4.0,>=0.3.5 in /usr/local/lib/python2.7/dist-packages (from django_peeringdb<0.5.0,==0.4.0) (0.3.5)
Requirement already satisfied: django<1.10,>=1.8 in /usr/local/lib/python2.7/dist-packages (from django_peeringdb<0.5.0,==0.4.0) (1.8.19)
Requirement already satisfied: ipaddress>=1 in /usr/lib/python2.7/dist-packages (from django_inet<0.4,>=0.3.2->django_peeringdb<0.5.0,==0.4.0) (1.0.17)
Requirement already satisfied: requests>=2.10.0 in /usr/lib/python2.7/dist-packages (from twentyc.rpc<0.4.0,>=0.3.5->django_peeringdb<0.5.0,==0.4.0) (2.18.4)
You are using pip version 18.1, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The directory '/tmp/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/nicolas/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: mysqlclient<2,>1 in /usr/local/lib/python2.7/dist-packages (1.4.1)
You are using pip version 18.1, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by vegu** [comment]
@McKay1717 please paste your peeringdb config and the outputs of `pip freeze`, thanks

**Comment by McKay1717** [comment]
```
$ cat .peeringdb/config.yaml 
database:
  engine: mysql
  host: 127.0.0.1
  name: peering
  password: **Secret**
  port: '3306'
  user: symphony
peeringdb:
  password: ''
  timeout: 0
  url: https://www.peeringdb.com/api
  user: ''
```

```
$ pip freeze
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
absl-py==0.2.0
asn1crypto==0.24.0
astor==0.6.2
atomicwrites==1.1.5
attrs==17.4.0
backports.functools-lru-cache==1.5
backports.weakref==1.0.post1
bcrypt==3.1.4
beautifulsoup4==4.6.3
bitarray==0.8.3
bleach==1.5.0
blinker==1.4
bottle==0.12.13
catkin-pkg==0.4.8
certifi==2018.8.24
chardet==3.0.4
click==6.7
click-datetime==0.2
configparser==3.5.0b2
CProfileV==1.0.7
cryptography==2.3
cvxopt==1.1.9
cycler==0.10.0
decorator==4.3.0
defusedxml==0.5.0
Django==1.8.19
django-countries==5.3.2
django-handleref==0.1.5
django-inet==0.3.2
django-peeringdb==0.4.0
dnspython==1.15.0
docopt==0.6.2
docutils==0.14
duplicity==0.7.17
empy==3.3.2
entrypoints==0.2.3.post3
enum34==1.1.6
et-xmlfile==1.0.1
fasteners==0.12.0
funcsigs==1.0.2
future==0.15.2
futures==3.2.0
gast==0.2.0
grpcio==1.11.0
gyp==0.1
html5lib==0.9999999
idna==2.6
ipaddr==2.2.0
ipaddress==1.0.17
jdcal==1.0
Jinja2==2.10
joblib==0.12.2
keyring==15.1.0
keyrings.alt==3.1
kiwisolver==1.0.1
lockfile==0.12.2
lxml==4.2.5
lz4==1.1.0
Markdown==2.6.11
MarkupSafe==1.1.0
matplotlib==2.2.2
mock==2.0.0
monotonic==1.0
more-itertools==4.2.0
munge==0.6.0
mysql-connector-python==8.0.11
mysql-utilities==1.6.4
mysqlclient==1.4.1
netifaces==0.10.7
notify2==0.3
numexpr==2.6.5
numpy==1.14.2
oauthlib==2.0.6
olefile==0.46
openpyxl==2.4.9
openvr==1.0.1701
pandas==0.23.3
paramiko==2.4.1
patsy==0.4.1+dev
pbr==4.0.2
peeringdb==0.6.1
pexpect==4.6.0
Pillow==5.2.0
pluggy==0.6.0
prettytable==0.7.2
protobuf==3.5.2.post1
psutil==5.4.6
pulseaudio-dlna==0.5.2
py==1.6.0
pyasn1==0.4.2
pycrypto==2.6.1
pygame===1.9.1release
Pygments==2.2.0
PyGObject==3.30.1
pyHS100==0.3.0
PyJWT==1.6.4
PyNaCl==1.2.1
pyodbc==4.0.22
pyOpenSSL==18.0.0
pyparsing==2.2.0
pyroute2==0.5.2
pysqlite==2.7.0
pytest==3.6.4
python-dateutil==2.6.1
python-gnupg==0.4.1
python-nmap==0.6.1
pytz==2018.5
pyxdg==0.25
PyYAML==3.12
requests==2.18.4
requests-oauthlib==0.8.0
roman==2.0.0
rosdep==0.12.2
rosdistro==0.6.9
rospkg==1.1.7
rospkg-modules==1.1.7
scapy-python3==0.25
scipy==1.1.0
scour==0.37
SecretStorage==2.3.1
setproctitle==1.1.10
simplejson==3.15.0
six==1.11.0
smstools==0.2.1
sqlparse==0.2.4
statsmodels==0.8.0
subprocess32==3.5.2
tables==3.4.4
tensorboard==1.7.0
tensorflow==1.7.0
termcolor==1.1.0
twentyc.rpc==0.3.5
typing==3.6.4
unicodecsv==0.14.1
urllib3==1.22
webencodings==0.5
Werkzeug==0.14.1
xlrd==1.1.0
xlwt==1.3.0
zeroconf==0.19.1
```

**Comment by vegu** [comment]
looks like the mysqlclient (1.4.1) it installs via depcheck is incompatible with django < 2 

`pip install mysqlclient==1.3.14` and it should work
