### ISSUE TITLE
ModuleNotFoundError: No module named 'client'

### ISSUE THREAD

**Issue by vgiotsas** [peeringdb/peeringdb-py#25]
When I try to run peeringdb I get the following error:

```
PS C:\windows\system32> peeringdb configure
Traceback (most recent call last):
  File "C:\Program Files\Python37\Scripts\peeringdb-script.py", line 11, in <module>
    load_entry_point('peeringdb==0.6.1', 'console_scripts', 'peeringdb')()
  File "C:\Users\Vasileios\AppData\Roaming\Python\Python37\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\Vasileios\AppData\Roaming\Python\Python37\site-packages\pkg_resources\__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "C:\Users\Vasileios\AppData\Roaming\Python\Python37\site-packages\pkg_resources\__init__.py", line 2411, in load
    return self.resolve()
  File "C:\Users\Vasileios\AppData\Roaming\Python\Python37\site-packages\pkg_resources\__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\program files\python37\lib\site-packages\peeringdb\__init__.py", line 3, in <module>
    from client import PeeringDB  # noqa
ModuleNotFoundError: No module named 'client'
```

I get the same error in two different systems:
1. Python 3.7.1 on Windows 10
2. Python 3.5.2 on Ubuntu 16.0.4

**Comment by FliesLikeABrick** [comment]
@vgiotsas  how did you install peeringdb -- from pip? if so, what version of the peeringdb package is installed?

**Comment by vgiotsas** [comment]
@FliesLikeABrick Yes, I installed peeringdb from pip, version 0.6.1

**Comment by aaglenn** [comment]
yes, it is definitely broken.

```
isidore$ doas pip3 install peeringdb
The directory '/home/aag/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/aag/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting peeringdb
  Downloading https://files.pythonhosted.org/packages/2d/d9/ed7220cecba25e7ef4115846fb4865258afbe13505b4a9fc6e55b1d74b0f/peeringdb-0.6.1.tar.gz
Collecting click>=5.1 (from peeringdb)
  Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
    100% |################################| 81kB 1.1MB/s 
Collecting munge>=0.1.5 (from peeringdb)
  Downloading https://files.pythonhosted.org/packages/1f/b6/8a03e444108605f3ccab7de0325c906ce024c9392203e32944083372cde4/munge-0.6.0.tar.gz
Requirement already satisfied: PyYAML>=3.11 in ./lib/python3.6/site-packages (from peeringdb) (3.13)
Collecting twentyc.rpc>=0.3.4 (from peeringdb)
  Downloading https://files.pythonhosted.org/packages/01/2d/554a3c51fc866f94345fd44865affb0b06b45f870362dee7af8496d1877e/twentyc.rpc-0.4.0.tar.gz
Requirement already satisfied: future<1,>=0.15.2 in ./lib/python3.6/site-packages (from munge>=0.1.5->peeringdb) (0.17.1)
Requirement already satisfied: requests<3,>=2.6.0 in ./lib/python3.6/site-packages (from munge>=0.1.5->peeringdb) (2.21.0)
Requirement already satisfied: six<2.0,>=1.10 in ./lib/python3.6/site-packages (from twentyc.rpc>=0.3.4->peeringdb) (1.12.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./lib/python3.6/site-packages (from requests<3,>=2.6.0->munge>=0.1.5->peeringdb) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in ./lib/python3.6/site-packages (from requests<3,>=2.6.0->munge>=0.1.5->peeringdb) (2.6)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in ./lib/python3.6/site-packages (from requests<3,>=2.6.0->munge>=0.1.5->peeringdb) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in ./lib/python3.6/site-packages (from requests<3,>=2.6.0->munge>=0.1.5->peeringdb) (2018.11.29)
Installing collected packages: click, munge, twentyc.rpc, peeringdb
  Running setup.py install for munge ... done
  Running setup.py install for twentyc.rpc ... done
  Running setup.py install for peeringdb ... done
Successfully installed click-7.0 munge-0.6.0 peeringdb-0.6.1 twentyc.rpc-0.4.0
isidore$ pe
peeringdb   perl        perl5.20.2  perl5.20.3  perlbug     perldoc     perlivp     
isidore$ peeringdb configure                                                                                                                                                                                                        
Traceback (most recent call last):
  File "/usr/local/bin/peeringdb", line 11, in <module>
    load_entry_point('peeringdb==0.6.1', 'console_scripts', 'peeringdb')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 479, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2703, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2321, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2327, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/peeringdb/__init__.py", line 3, in <module>
    from client import PeeringDB  # noqa
ModuleNotFoundError: No module named 'client'
isidore$ pip3 -V
pip 19.0.3 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)
isidore$ uname -a
OpenBSD isidore.aagico.local 6.5 GENERIC.MP#840 amd64
```

**Comment by tkoch96** [comment]
I solved this by replacing "client" with peeringdb.client

Then it worked fine

**Comment by JoshWeepie** [comment]
Is there going to be a fix for this instead of tkoch96's workaround?

**Comment by arnoldnipper** [comment]
@peeringdb/20c please take care

**Comment by grizz** [comment]
I don't think this is still valid, please re-open if it is.
