### ISSUE TITLE
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation'

### ISSUE THREAD

**Issue by egecemkirci** [peeringdb/peeringdb-py#60]
I am trying to follow the tutorial instructions, but the following command resulted in the following error log: 

~$ peeringdb get net1

```
Traceback (most recent call last):
  File "/home/ekirci/.local/bin/peeringdb", line 11, in <module>
    sys.exit(main())
  File "/home/ekirci/.local/lib/python3.9/site-packages/peeringdb/cli.py", line 68, in main
    return handler(config=cfg, **vars(options))
  File "/home/ekirci/.local/lib/python3.9/site-packages/peeringdb/commands.py", line 18, in _wrapped
    r = func(*a, **k)
  File "/home/ekirci/.local/lib/python3.9/site-packages/peeringdb/commands.py", line 87, in handle
    client = Client(config)
  File "/home/ekirci/.local/lib/python3.9/site-packages/peeringdb/client.py", line 48, in __init__
    initialize_backend(orm_name, **orm_config)
  File "/home/ekirci/.local/lib/python3.9/site-packages/peeringdb/__init__.py", line 87, in initialize_backend
    B = supportmod.load_backend(**kwargs)
  File "/home/ekirci/.local/lib/python3.9/site-packages/django_peeringdb/client_adaptor/load.py", line 40, in load_backend
    configure(**settings)
  File "/home/ekirci/.local/lib/python3.9/site-packages/django_peeringdb/client_adaptor/setup.py", line 28, in configure
    setup()
  File "/home/ekirci/.local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ekirci/.local/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/ekirci/.local/lib/python3.9/site-packages/django/apps/config.py", line 300, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ekirci/.local/lib/python3.9/site-packages/django_peeringdb/models/__init__.py", line 8, in <module>
    from django_peeringdb.models.concrete import *  # noqa
  File "/home/ekirci/.local/lib/python3.9/site-packages/django_peeringdb/models/concrete.py", line 3, in <module>
    from django.utils.translation import ugettext_lazy as _
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/home/ekirci/.local/lib/python3.9/site-packages/django/utils/translation/__init__.py)
```

**Comment by grizz** [comment]
This was fixed with a django-peeringdb release.
